# Generated by Django 4.2.2 on 2023-06-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
    ]
